[project]
name = "libvirt-compose"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
[tool.uv]
# Rejection: Don't use any package version published after March 1st, 2026
exclude-newer = "2026-05-05T00:00:00Z"
[project.scripts]
libvirt-compose = "libvirt_compose.__main__:main"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/libvirt_compose"]